server:
  port: 8084
# Application Name

# -- Application Configuration --
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///D:/BootCamp/Modulo Spring++/config-repo
          default-label: main